### ISSUE TITLE
kcd-recompile / Watching nested properties

### ISSUE THREAD

**Issue by mica16** [kentcdodds/kcd-angular#2]
Hi,

First, thanks for the great directive ``` kcd-recompile ```.

I noticed that it's no possible to watch for nested properties in the current directive.
For instance, let's suppose in the controlleur: 
``` 
$scope.person = {};
$scope.person.mud = 'happy';
```  

In HTML I would have (inside an ng-repeat="persons"): 
```
<div kcd-recompile="person"> 
   <span>{{::person.mud}}</span>
</div>
```

However, as a nested property, recompilation would not happen if I do: 
``` 
$scope.person.mud = 'sad'; 
```

The fix that I did is to add the argument "true" to the watch made by the directive like so:

```
var stopWatching = scope.$parent.$watch(attrs.kcdRecompile, function (_new, _old) {
                        var useBoolean = attrs.hasOwnProperty('useBoolean');
                        if ((useBoolean && (!_new || _new === 'false')) || (!useBoolean && (!_new || _new === _old))) {
                            return;
                        }
                        // reset kcdRecompile to false if we're using a boolean
                        if (useBoolean) {
                            $parse(attrs.kcdRecompile).assign(scope.$parent, false);
                        }

                        // recompile
                        var newEl = $compile(template)(scope.$parent);
                        $el.replaceWith(newEl);

                        // Destroy old scope, reassign new scope.
                        stopWatching();
                        scope.$destroy();
                    }, true);  //here, adding true to enable watch on nested properties
```

Is it possible to merge it in the current directive? Or better: adding it as an option:  
``` 
<div kcd-recompile="person" nested="true"> 
``` 

What do you think?

Thanks.

**Comment by kasperlewau** [comment]
Would it make sense to handle detection for the user automagically? Speaking from personal experience, It's not very common to look for the existence of an object in itself - it's a lot more common to look at the existence/changes of properties in said object. 

Sort of like so:  

```js
scope.$watch(attrs.kcdRecompile, function(_new, _old) {
  /** redacted **/  
}, typeof $parse(attrs.kcdRecompile)(scope) === 'object'); // true|false;
```

I do apologise if this is considered a [necro](http://www.urbandictionary.com/define.php?term=necropost).

**Comment by kentcdodds** [comment]
@kasperlewau, nope you're good. That's a good idea. I don't really use `kcd-recompile` at all, but I'd happily accept a PR that updates it to do as you illustrated :-)

**Comment by websirnik** [comment]
@kentcdodds Curious why you are not using `kcd-recompile` anymore. Is there a better way?

**Comment by kentcdodds** [comment]
I just don't do Angular anymore
