### ISSUE TITLE
kcd-recompile on ng-repeat

### ISSUE THREAD

**Issue by rmsint** [kentcdodds/kcd-angular#4]
Hi Kent,

After reading your blog about recompiling templates, I started experimenting with the directive and found it gives some strange results when put on the same element `ng-repeat` is on. I experimented using angulars transclusion and that solved the issue. Not sure if that prevents old scopes and elements dangling around, imho it should.

Anyhow, here are the plunkers of the experiments, maybe it is of use:
* [plunker showing the issue with `ng-repeat`](http://plnkr.co/edit/evK5jY3pYHaZKGs7dZk8)
* [plunker using transclusion](http://plnkr.co/edit/MfYzEE0VlzGhbPy7sdzO?p=preview)

**Comment by kentcdodds** [comment]
I think you're correct. Would you like to submit a PR with your fix? Thanks for finding this issue!

**Comment by rmsint** [comment]
Done
